blank_issues_enabled: true
contact_links:
  - name: Translation bug
    url: https://github.com/progit/progit2/blob/main/TRANSLATING.md
    about: Refer to this table to find out where to report translation bugs.

  - name: Report bugs for git-scm.com site
    url: https://github.com/git/git-scm.com/issues/
    about: Please report problems with the git-scm.com site there.

  - name: Bug is about Git program itself
    url: https://git-scm.com/community
    about: Please report problems with the Git program there.

  - name: Bug is about Git for Windows
    url: https://github.com/git-for-windows/git/issues
    about: Please report problems with Git for Windows there.
