version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "ben"
    default_labels:
      - "dependabot"
